[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish StoreApi.Api/StoreApi.Api.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/StoreApi.Api.dll"