import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppSidebar } from "@/components/layout/sideBar/app-sidebar";
import QueryProvider from "@/providers/QueryProvider";
import { ModeToggle } from "@/components/toggle/mode-toggle";
import { HeaderSearch } from "@/components/layout/nav-bar/header-search";
import { Separator } from "@/components/ui/separator";
import { Suspense } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import Notifictaion from "@/components/toggle/notifictaion";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BusinessLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <TooltipProvider>
          <SidebarProvider>
            <AppSidebar />
            <div className="grow flex flex-col min-h-screen w-full">
              <Header />
              <main className="flex-1 w-full relative">{children}</main>
              <Toaster />
            </div>
          </SidebarProvider>
        </TooltipProvider>
      </ThemeProvider>
    </QueryProvider>
  );
}

function Header() {
  return (
    <header className="w-full flex h-14 shrink-0 items-center justify-between gap-4 border-b bg-white/50 dark:bg-zinc-950/50 backdrop-blur-md px-4 sticky top-0 z-30 transition-colors duration-300">
      <div className="flex items-center gap-3 flex-1 min-w-0">
        <SidebarTrigger className="-ml-1 text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-900 rounded-lg" />
        <Separator orientation="vertical" className="h-4" />
        <Suspense fallback={<Skeleton className="h-4 w-4" />}>
          <HeaderSearch />
        </Suspense>
      </div>
      <div className="flex items-center gap-2">
        <ModeToggle />
        <Notifictaion />
      </div>
    </header>
  );
}